### PR TITLE
use a queue shared among fastfall instances

### PR DESCRIPTION
**Pull request by paolochiodi**
In my assumption this will allow some performance gain when fastball is used many times in parallel

### CODE REVIEW

**Comment by mcollina** [comment]
Not really, the whole concept is those holders are specialized for a specific problem. V8 will inline functions and so on, so it will be faster in the end.

**Comment by mcollina** [comment]
Maybe it's not a very bad idea.

**Comment by paolochiodi** [comment]
@mcollina do you plan to work on this in the future? Otherwise I'd close the PR since it's becoming a bit old

**Comment by mcollina** [comment]
Please close :).
Il giorno mer 5 ott 2016 alle 05:03 Paolo Chiodi notifications@github.com
ha scritto:

**Pull request closed without merging**
